[install]
is_configured = false
state = enabled

[launcher]
author = UniFi App for Splunk
description = Consolidated dashboards and syslog correlation for UniFi gear. Enriches device/client IDs to names/IP/MAC and links telemetry, asset and syslog data with drilldowns. Companion to TA_unifi_ng.
version = 1.0.2

[ui]
is_visible = true
label = UniFi App for Splunk
supported_themes = light, dark

[package]
check_for_updates = true
id = unifi_app_for_splunk
